//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace SunacCADApp.WebService.IDM.Public {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PUBLIC_SUNAC_301_queryIdmOrgData_ptt-binding", Namespace="http://www.ekingwin.com/esb/PUBLIC_SUNAC_301_queryIdmOrgData")]
    public partial class PUBLIC_SUNAC_301_queryIdmOrgData_pttbindingQSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Header commonHeaderField;
        
        private System.Threading.SendOrPostCallback PUBLIC_SUNAC_301_queryIdmOrgDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PUBLIC_SUNAC_301_queryIdmOrgData_pttbindingQSService() {
            this.Url = global::SunacCADApp.Properties.Settings.Default.SunacCADApp_WebService_IDM_Public_PUBLIC_SUNAC_301_queryIdmOrgData_ptt_bindingQSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Header commonHeader {
            get {
                return this.commonHeaderField;
            }
            set {
                this.commonHeaderField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PUBLIC_SUNAC_301_queryIdmOrgDataCompletedEventHandler PUBLIC_SUNAC_301_queryIdmOrgDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("commonHeader", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("PUBLIC_SUNAC_301_queryIdmOrgData", RequestNamespace="http://www.ekingwin.com/esb/PUBLIC_SUNAC_301_queryIdmOrgData", ResponseElementName="response", ResponseNamespace="http://www.ekingwin.com/esb/PUBLIC_SUNAC_301_queryIdmOrgData", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("HEADER")]
        public HEADER PUBLIC_SUNAC_301_queryIdmOrgData(queryDto queryDto, out string LIST) {
            object[] results = this.Invoke("PUBLIC_SUNAC_301_queryIdmOrgData", new object[] {
                        queryDto});
            LIST = ((string)(results[1]));
            return ((HEADER)(results[0]));
        }
        
        /// <remarks/>
        public void PUBLIC_SUNAC_301_queryIdmOrgDataAsync(queryDto queryDto) {
            this.PUBLIC_SUNAC_301_queryIdmOrgDataAsync(queryDto, null);
        }
        
        /// <remarks/>
        public void PUBLIC_SUNAC_301_queryIdmOrgDataAsync(queryDto queryDto, object userState) {
            if ((this.PUBLIC_SUNAC_301_queryIdmOrgDataOperationCompleted == null)) {
                this.PUBLIC_SUNAC_301_queryIdmOrgDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPUBLIC_SUNAC_301_queryIdmOrgDataOperationCompleted);
            }
            this.InvokeAsync("PUBLIC_SUNAC_301_queryIdmOrgData", new object[] {
                        queryDto}, this.PUBLIC_SUNAC_301_queryIdmOrgDataOperationCompleted, userState);
        }
        
        private void OnPUBLIC_SUNAC_301_queryIdmOrgDataOperationCompleted(object arg) {
            if ((this.PUBLIC_SUNAC_301_queryIdmOrgDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PUBLIC_SUNAC_301_queryIdmOrgDataCompleted(this, new PUBLIC_SUNAC_301_queryIdmOrgDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ekingwin.com/esb/header/v1")]
    [System.Xml.Serialization.XmlRootAttribute("commonHeader", Namespace="http://www.ekingwin.com/esb/header/v1", IsNullable=false)]
    public partial class Header : System.Web.Services.Protocols.SoapHeader {
        
        private string bIZTRANSACTIONIDField;
        
        private string cOUNTField;
        
        private string cONSUMERField;
        
        private string sRVLEVELField;
        
        private string aCCOUNTField;
        
        private string pASSWORDField;
        
        /// <remarks/>
        public string BIZTRANSACTIONID {
            get {
                return this.bIZTRANSACTIONIDField;
            }
            set {
                this.bIZTRANSACTIONIDField = value;
            }
        }
        
        /// <remarks/>
        public string COUNT {
            get {
                return this.cOUNTField;
            }
            set {
                this.cOUNTField = value;
            }
        }
        
        /// <remarks/>
        public string CONSUMER {
            get {
                return this.cONSUMERField;
            }
            set {
                this.cONSUMERField = value;
            }
        }
        
        /// <remarks/>
        public string SRVLEVEL {
            get {
                return this.sRVLEVELField;
            }
            set {
                this.sRVLEVELField = value;
            }
        }
        
        /// <remarks/>
        public string ACCOUNT {
            get {
                return this.aCCOUNTField;
            }
            set {
                this.aCCOUNTField = value;
            }
        }
        
        /// <remarks/>
        public string PASSWORD {
            get {
                return this.pASSWORDField;
            }
            set {
                this.pASSWORDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ekingwin.com/esb/PUBLIC_SUNAC_301_queryIdmOrgData")]
    public partial class HEADER {
        
        private string bIZTRANSACTIONIDField;
        
        private string rESULTField;
        
        private string eRRORCODEField;
        
        private string eRRORINFOField;
        
        private string cOMMENTSField;
        
        private string sUCCESSCOUNTField;
        
        /// <remarks/>
        public string BIZTRANSACTIONID {
            get {
                return this.bIZTRANSACTIONIDField;
            }
            set {
                this.bIZTRANSACTIONIDField = value;
            }
        }
        
        /// <remarks/>
        public string RESULT {
            get {
                return this.rESULTField;
            }
            set {
                this.rESULTField = value;
            }
        }
        
        /// <remarks/>
        public string ERRORCODE {
            get {
                return this.eRRORCODEField;
            }
            set {
                this.eRRORCODEField = value;
            }
        }
        
        /// <remarks/>
        public string ERRORINFO {
            get {
                return this.eRRORINFOField;
            }
            set {
                this.eRRORINFOField = value;
            }
        }
        
        /// <remarks/>
        public string COMMENTS {
            get {
                return this.cOMMENTSField;
            }
            set {
                this.cOMMENTSField = value;
            }
        }
        
        /// <remarks/>
        public string SUCCESSCOUNT {
            get {
                return this.sUCCESSCOUNTField;
            }
            set {
                this.sUCCESSCOUNTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ekingwin.com/esb/PUBLIC_SUNAC_301_queryIdmOrgData")]
    public partial class queryDto {
        
        private string beginDateField;
        
        private string endDateField;
        
        private string pageNoField;
        
        private string pageRowNoField;
        
        private string systemIDField;
        
        /// <remarks/>
        public string beginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
            }
        }
        
        /// <remarks/>
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public string pageNo {
            get {
                return this.pageNoField;
            }
            set {
                this.pageNoField = value;
            }
        }
        
        /// <remarks/>
        public string pageRowNo {
            get {
                return this.pageRowNoField;
            }
            set {
                this.pageRowNoField = value;
            }
        }
        
        /// <remarks/>
        public string systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void PUBLIC_SUNAC_301_queryIdmOrgDataCompletedEventHandler(object sender, PUBLIC_SUNAC_301_queryIdmOrgDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PUBLIC_SUNAC_301_queryIdmOrgDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PUBLIC_SUNAC_301_queryIdmOrgDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HEADER Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HEADER)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string LIST {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591