//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace SunacCADApp.WebService.UpdataAndApproveFlow {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CAD_SUNAC_565_UpdateAndApproveFlow_ptt-binding", Namespace="http://www.ekingwin.com/esb/CAD_SUNAC_565_UpdateAndApproveFlow")]
    public partial class CAD_SUNAC_565_UpdateAndApproveFlow_pttbindingQSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CAD_SUNAC_565_UpdateAndApproveFlowOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CAD_SUNAC_565_UpdateAndApproveFlow_pttbindingQSService() {
            this.Url = global::SunacCADApp.Properties.Settings.Default.SunacCADApp_WebService_UpdataAndApproveFlow_CAD_SUNAC_565_UpdateAndApproveFlow_ptt_bindingQSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CAD_SUNAC_565_UpdateAndApproveFlowCompletedEventHandler CAD_SUNAC_565_UpdateAndApproveFlowCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CAD_SUNAC_565_UpdateAndApproveFlow", RequestNamespace="http://www.ekingwin.com/esb/CAD_SUNAC_565_UpdateAndApproveFlow", ResponseElementName="CAD_SUNAC_565_UpdateAndApproveFlow_RSP", ResponseNamespace="http://www.ekingwin.com/esb/CAD_SUNAC_565_UpdateAndApproveFlow", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("E_RESPONSE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public E_RESPONSE CAD_SUNAC_565_UpdateAndApproveFlow([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] I_REQUEST I_REQUEST) {
            object[] results = this.Invoke("CAD_SUNAC_565_UpdateAndApproveFlow", new object[] {
                        I_REQUEST});
            return ((E_RESPONSE)(results[0]));
        }
        
        /// <remarks/>
        public void CAD_SUNAC_565_UpdateAndApproveFlowAsync(I_REQUEST I_REQUEST) {
            this.CAD_SUNAC_565_UpdateAndApproveFlowAsync(I_REQUEST, null);
        }
        
        /// <remarks/>
        public void CAD_SUNAC_565_UpdateAndApproveFlowAsync(I_REQUEST I_REQUEST, object userState) {
            if ((this.CAD_SUNAC_565_UpdateAndApproveFlowOperationCompleted == null)) {
                this.CAD_SUNAC_565_UpdateAndApproveFlowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCAD_SUNAC_565_UpdateAndApproveFlowOperationCompleted);
            }
            this.InvokeAsync("CAD_SUNAC_565_UpdateAndApproveFlow", new object[] {
                        I_REQUEST}, this.CAD_SUNAC_565_UpdateAndApproveFlowOperationCompleted, userState);
        }
        
        private void OnCAD_SUNAC_565_UpdateAndApproveFlowOperationCompleted(object arg) {
            if ((this.CAD_SUNAC_565_UpdateAndApproveFlowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CAD_SUNAC_565_UpdateAndApproveFlowCompleted(this, new CAD_SUNAC_565_UpdateAndApproveFlowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ekingwin.com/esb/CAD_SUNAC_565_UpdateAndApproveFlow")]
    public partial class I_REQUEST {
        
        private REQ_BASEINFO rEQ_BASEINFOField;
        
        private REQ_ITEM[] mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public REQ_BASEINFO REQ_BASEINFO {
            get {
                return this.rEQ_BASEINFOField;
            }
            set {
                this.rEQ_BASEINFOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public REQ_ITEM[] MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ekingwin.com/esb/header/v1")]
    public partial class REQ_BASEINFO {
        
        private string rEQ_TRACE_IDField;
        
        private string rEQ_SEND_TIMEField;
        
        private string rEQ_SRC_SYSField;
        
        private string rEQ_TAR_SYSField;
        
        private string rEQ_SERVER_NAMEField;
        
        private string rEQ_SYN_FLAGField;
        
        private string rEQ_BSN_IDField;
        
        private string rEQ_RETRY_TIMESField;
        
        private string rEQ_REPEAT_FLAGField;
        
        private string rEQ_REPEAT_CYCLEField;
        
        private string bIZTRANSACTIONIDField;
        
        private string cOUNTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REQ_TRACE_ID {
            get {
                return this.rEQ_TRACE_IDField;
            }
            set {
                this.rEQ_TRACE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REQ_SEND_TIME {
            get {
                return this.rEQ_SEND_TIMEField;
            }
            set {
                this.rEQ_SEND_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REQ_SRC_SYS {
            get {
                return this.rEQ_SRC_SYSField;
            }
            set {
                this.rEQ_SRC_SYSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REQ_TAR_SYS {
            get {
                return this.rEQ_TAR_SYSField;
            }
            set {
                this.rEQ_TAR_SYSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REQ_SERVER_NAME {
            get {
                return this.rEQ_SERVER_NAMEField;
            }
            set {
                this.rEQ_SERVER_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REQ_SYN_FLAG {
            get {
                return this.rEQ_SYN_FLAGField;
            }
            set {
                this.rEQ_SYN_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REQ_BSN_ID {
            get {
                return this.rEQ_BSN_IDField;
            }
            set {
                this.rEQ_BSN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REQ_RETRY_TIMES {
            get {
                return this.rEQ_RETRY_TIMESField;
            }
            set {
                this.rEQ_RETRY_TIMESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REQ_REPEAT_FLAG {
            get {
                return this.rEQ_REPEAT_FLAGField;
            }
            set {
                this.rEQ_REPEAT_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REQ_REPEAT_CYCLE {
            get {
                return this.rEQ_REPEAT_CYCLEField;
            }
            set {
                this.rEQ_REPEAT_CYCLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIZTRANSACTIONID {
            get {
                return this.bIZTRANSACTIONIDField;
            }
            set {
                this.bIZTRANSACTIONIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COUNT {
            get {
                return this.cOUNTField;
            }
            set {
                this.cOUNTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ekingwin.com/esb/header/v1")]
    public partial class RSP_BASEINFO {
        
        private string rSP_TRACE_IDField;
        
        private string rSP_REQ_TRACEIDField;
        
        private string rSP_SEND_TIMEField;
        
        private string rSP_SRC_SYSField;
        
        private string rSP_TAR_SYSField;
        
        private string rSP_SERVER_NAMEField;
        
        private string rSP_BSN_IDField;
        
        private string rSP_RETRY_TIMESField;
        
        private string rSP_STATUS_CODEField;
        
        private string rSP_STATUS_MSGField;
        
        private string bIZTRANSACTIONIDField;
        
        private string cOUNTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RSP_TRACE_ID {
            get {
                return this.rSP_TRACE_IDField;
            }
            set {
                this.rSP_TRACE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RSP_REQ_TRACEID {
            get {
                return this.rSP_REQ_TRACEIDField;
            }
            set {
                this.rSP_REQ_TRACEIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RSP_SEND_TIME {
            get {
                return this.rSP_SEND_TIMEField;
            }
            set {
                this.rSP_SEND_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RSP_SRC_SYS {
            get {
                return this.rSP_SRC_SYSField;
            }
            set {
                this.rSP_SRC_SYSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RSP_TAR_SYS {
            get {
                return this.rSP_TAR_SYSField;
            }
            set {
                this.rSP_TAR_SYSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RSP_SERVER_NAME {
            get {
                return this.rSP_SERVER_NAMEField;
            }
            set {
                this.rSP_SERVER_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RSP_BSN_ID {
            get {
                return this.rSP_BSN_IDField;
            }
            set {
                this.rSP_BSN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RSP_RETRY_TIMES {
            get {
                return this.rSP_RETRY_TIMESField;
            }
            set {
                this.rSP_RETRY_TIMESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RSP_STATUS_CODE {
            get {
                return this.rSP_STATUS_CODEField;
            }
            set {
                this.rSP_STATUS_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RSP_STATUS_MSG {
            get {
                return this.rSP_STATUS_MSGField;
            }
            set {
                this.rSP_STATUS_MSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIZTRANSACTIONID {
            get {
                return this.bIZTRANSACTIONIDField;
            }
            set {
                this.bIZTRANSACTIONIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COUNT {
            get {
                return this.cOUNTField;
            }
            set {
                this.cOUNTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ekingwin.com/esb/CAD_SUNAC_565_UpdateAndApproveFlow")]
    public partial class E_RESPONSE {
        
        private RSP_BASEINFO rSP_BASEINFOField;
        
        private E_RESPONSERSP_ITEM[] mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RSP_BASEINFO RSP_BASEINFO {
            get {
                return this.rSP_BASEINFOField;
            }
            set {
                this.rSP_BASEINFOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RSP_ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public E_RESPONSERSP_ITEM[] MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ekingwin.com/esb/CAD_SUNAC_565_UpdateAndApproveFlow")]
    public partial class E_RESPONSERSP_ITEM {
        
        private string sTATUSCODEField;
        
        private string sTATUSMESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATUSCODE {
            get {
                return this.sTATUSCODEField;
            }
            set {
                this.sTATUSCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATUSMESSAGE {
            get {
                return this.sTATUSMESSAGEField;
            }
            set {
                this.sTATUSMESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ekingwin.com/esb/CAD_SUNAC_565_UpdateAndApproveFlow")]
    public partial class REQ_ITEM {
        
        private string procInstIdField;
        
        private string jobidField;
        
        private string xmldataField;
        
        private string useridField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string procInstId {
            get {
                return this.procInstIdField;
            }
            set {
                this.procInstIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jobid {
            get {
                return this.jobidField;
            }
            set {
                this.jobidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string xmldata {
            get {
                return this.xmldataField;
            }
            set {
                this.xmldataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userid {
            get {
                return this.useridField;
            }
            set {
                this.useridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void CAD_SUNAC_565_UpdateAndApproveFlowCompletedEventHandler(object sender, CAD_SUNAC_565_UpdateAndApproveFlowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CAD_SUNAC_565_UpdateAndApproveFlowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CAD_SUNAC_565_UpdateAndApproveFlowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public E_RESPONSE Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((E_RESPONSE)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591