//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunacCADApp.Test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://des.sunac.com.cn/SunacCADService.asmx")]
        public string SunacCADApp_Test_SunacCadService_ArgumentSettingService {
            get {
                return ((string)(this["SunacCADApp_Test_SunacCadService_ArgumentSettingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.2.219:8001/WP_SUNAC/APP_IDM_SERVICES/Proxy_Services/TA_EOP/IDM_SUN" +
            "AC_392_validatePwd_PS")]
        public string SunacCADApp_Test_WebIDMSUNACValidatePwd_IDM_SUNAC_392_validatePwd_ptt_bindingQSService {
            get {
                return ((string)(this["SunacCADApp_Test_WebIDMSUNACValidatePwd_IDM_SUNAC_392_validatePwd_ptt_bindingQSSe" +
                    "rvice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://des.sunac.com.cn/BMPService.asmx")]
        public string SunacCADApp_Test_WebBMPService_BMPService {
            get {
                return ((string)(this["SunacCADApp_Test_WebBMPService_BMPService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ades.sunac.com.cn/SunacCADService.asmx")]
        public string SunacCADApp_Test_adesService_ArgumentSettingService {
            get {
                return ((string)(this["SunacCADApp_Test_adesService_ArgumentSettingService"]));
            }
        }
    }
}
