//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunacCADApp.ServiceReference1 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ekingwin.com/esb/IDM_SUNAC_392_validatePwd")]
    public partial class QueryFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private errorType queryFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("QueryFault", Order=0)]
        public errorType QueryFault1 {
            get {
                return this.queryFault1Field;
            }
            set {
                this.queryFault1Field = value;
                this.RaisePropertyChanged("QueryFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ekingwin.com/esb/error/v1")]
    public partial class errorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private System.DateTime timestampField;
        
        private object errorDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public object ErrorDetails {
            get {
                return this.errorDetailsField;
            }
            set {
                this.errorDetailsField = value;
                this.RaisePropertyChanged("ErrorDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ekingwin.com/esb/header/v1")]
    public partial class Header : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bIZTRANSACTIONIDField;
        
        private string cOUNTField;
        
        private string cONSUMERField;
        
        private System.DateTime sRVLEVELField;
        
        private string aCCOUNTField;
        
        private string pASSWORDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BIZTRANSACTIONID {
            get {
                return this.bIZTRANSACTIONIDField;
            }
            set {
                this.bIZTRANSACTIONIDField = value;
                this.RaisePropertyChanged("BIZTRANSACTIONID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string COUNT {
            get {
                return this.cOUNTField;
            }
            set {
                this.cOUNTField = value;
                this.RaisePropertyChanged("COUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CONSUMER {
            get {
                return this.cONSUMERField;
            }
            set {
                this.cONSUMERField = value;
                this.RaisePropertyChanged("CONSUMER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime SRVLEVEL {
            get {
                return this.sRVLEVELField;
            }
            set {
                this.sRVLEVELField = value;
                this.RaisePropertyChanged("SRVLEVEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ACCOUNT {
            get {
                return this.aCCOUNTField;
            }
            set {
                this.aCCOUNTField = value;
                this.RaisePropertyChanged("ACCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PASSWORD {
            get {
                return this.pASSWORDField;
            }
            set {
                this.pASSWORDField = value;
                this.RaisePropertyChanged("PASSWORD");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ekingwin.com/esb/IDM_SUNAC_392_validatePwd")]
    public partial class HEADER : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bIZTRANSACTIONIDField;
        
        private string rESULTField;
        
        private string eRRORCODEField;
        
        private string eRRORINFOField;
        
        private string cOMMENTSField;
        
        private string sUCCESSCOUNTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BIZTRANSACTIONID {
            get {
                return this.bIZTRANSACTIONIDField;
            }
            set {
                this.bIZTRANSACTIONIDField = value;
                this.RaisePropertyChanged("BIZTRANSACTIONID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RESULT {
            get {
                return this.rESULTField;
            }
            set {
                this.rESULTField = value;
                this.RaisePropertyChanged("RESULT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ERRORCODE {
            get {
                return this.eRRORCODEField;
            }
            set {
                this.eRRORCODEField = value;
                this.RaisePropertyChanged("ERRORCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ERRORINFO {
            get {
                return this.eRRORINFOField;
            }
            set {
                this.eRRORINFOField = value;
                this.RaisePropertyChanged("ERRORINFO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string COMMENTS {
            get {
                return this.cOMMENTSField;
            }
            set {
                this.cOMMENTSField = value;
                this.RaisePropertyChanged("COMMENTS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SUCCESSCOUNT {
            get {
                return this.sUCCESSCOUNTField;
            }
            set {
                this.sUCCESSCOUNTField = value;
                this.RaisePropertyChanged("SUCCESSCOUNT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ekingwin.com/esb/IDM_SUNAC_392_validatePwd")]
    public partial class user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ekingwin.com/esb/IDM_SUNAC_392_validatePwd", ConfigurationName="ServiceReference1.IDM_SUNAC_392_validatePwd_ptt")]
    public interface IDM_SUNAC_392_validatePwd_ptt {
        
        // CODEGEN: 操作 IDM_SUNAC_392_validatePwd 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="IDM_SUNAC_392_validatePwd", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SunacCADApp.ServiceReference1.QueryFault), Action="IDM_SUNAC_392_validatePwd", Name="QueryFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Header))]
        SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwdResponse IDM_SUNAC_392_validatePwd(SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="IDM_SUNAC_392_validatePwd", ReplyAction="*")]
        System.Threading.Tasks.Task<SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwdResponse> IDM_SUNAC_392_validatePwdAsync(SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ekingwin.com/esb/IDM_SUNAC_392_validatePwd")]
    public partial class IDM_SUNAC_392_validatePwd : object, System.ComponentModel.INotifyPropertyChanged {
        
        private user userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ekingwin.com/esb/IDM_SUNAC_392_validatePwd")]
    public partial class response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HEADER hEADERField;
        
        private string lISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public HEADER HEADER {
            get {
                return this.hEADERField;
            }
            set {
                this.hEADERField = value;
                this.RaisePropertyChanged("HEADER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LIST {
            get {
                return this.lISTField;
            }
            set {
                this.lISTField = value;
                this.RaisePropertyChanged("LIST");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IDM_SUNAC_392_validatePwdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ekingwin.com/esb/header/v1")]
        public SunacCADApp.ServiceReference1.Header commonHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ekingwin.com/esb/IDM_SUNAC_392_validatePwd", Order=0)]
        public SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwd IDM_SUNAC_392_validatePwd;
        
        public IDM_SUNAC_392_validatePwdRequest() {
        }
        
        public IDM_SUNAC_392_validatePwdRequest(SunacCADApp.ServiceReference1.Header commonHeader, SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwd IDM_SUNAC_392_validatePwd) {
            this.commonHeader = commonHeader;
            this.IDM_SUNAC_392_validatePwd = IDM_SUNAC_392_validatePwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IDM_SUNAC_392_validatePwdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ekingwin.com/esb/header/v1")]
        public SunacCADApp.ServiceReference1.Header commonHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ekingwin.com/esb/IDM_SUNAC_392_validatePwd", Order=0)]
        public SunacCADApp.ServiceReference1.response response;
        
        public IDM_SUNAC_392_validatePwdResponse() {
        }
        
        public IDM_SUNAC_392_validatePwdResponse(SunacCADApp.ServiceReference1.Header commonHeader, SunacCADApp.ServiceReference1.response response) {
            this.commonHeader = commonHeader;
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDM_SUNAC_392_validatePwd_pttChannel : SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwd_ptt, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DM_SUNAC_392_validatePwd_pttClient : System.ServiceModel.ClientBase<SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwd_ptt>, SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwd_ptt {
        
        public DM_SUNAC_392_validatePwd_pttClient() {
        }
        
        public DM_SUNAC_392_validatePwd_pttClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DM_SUNAC_392_validatePwd_pttClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DM_SUNAC_392_validatePwd_pttClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DM_SUNAC_392_validatePwd_pttClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwdResponse SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwd_ptt.IDM_SUNAC_392_validatePwd(SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwdRequest request) {
            return base.Channel.IDM_SUNAC_392_validatePwd(request);
        }
        
        public SunacCADApp.ServiceReference1.response IDM_SUNAC_392_validatePwd(ref SunacCADApp.ServiceReference1.Header commonHeader, SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwd IDM_SUNAC_392_validatePwd1) {
            SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwdRequest inValue = new SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwdRequest();
            inValue.commonHeader = commonHeader;
            inValue.IDM_SUNAC_392_validatePwd = IDM_SUNAC_392_validatePwd1;
            SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwdResponse retVal = ((SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwd_ptt)(this)).IDM_SUNAC_392_validatePwd(inValue);
            commonHeader = retVal.commonHeader;
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwdResponse> SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwd_ptt.IDM_SUNAC_392_validatePwdAsync(SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwdRequest request) {
            return base.Channel.IDM_SUNAC_392_validatePwdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwdResponse> IDM_SUNAC_392_validatePwdAsync(SunacCADApp.ServiceReference1.Header commonHeader, SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwd IDM_SUNAC_392_validatePwd) {
            SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwdRequest inValue = new SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwdRequest();
            inValue.commonHeader = commonHeader;
            inValue.IDM_SUNAC_392_validatePwd = IDM_SUNAC_392_validatePwd;
            return ((SunacCADApp.ServiceReference1.IDM_SUNAC_392_validatePwd_ptt)(this)).IDM_SUNAC_392_validatePwdAsync(inValue);
        }
    }
}
