//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace SunacCADApp.WebService932 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IDM_SUNAC_392_validatePwd_ptt-binding", Namespace="http://www.ekingwin.com/esb/IDM_SUNAC_392_validatePwd")]
    public partial class IDM_SUNAC_392_validatePwd_pttbindingQSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Header commonHeaderField;
        
        private System.Threading.SendOrPostCallback IDM_SUNAC_392_validatePwdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IDM_SUNAC_392_validatePwd_pttbindingQSService() {
            this.Url = global::SunacCADApp.Properties.Settings.Default.SunacCADApp_WebService932_IDM_SUNAC_392_validatePwd_ptt_bindingQSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Header commonHeader {
            get {
                return this.commonHeaderField;
            }
            set {
                this.commonHeaderField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IDM_SUNAC_392_validatePwdCompletedEventHandler IDM_SUNAC_392_validatePwdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("commonHeader", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("IDM_SUNAC_392_validatePwd", RequestNamespace="http://www.ekingwin.com/esb/IDM_SUNAC_392_validatePwd", ResponseElementName="response", ResponseNamespace="http://www.ekingwin.com/esb/IDM_SUNAC_392_validatePwd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("HEADER")]
        public HEADER IDM_SUNAC_392_validatePwd(user user, out string LIST) {
            object[] results = this.Invoke("IDM_SUNAC_392_validatePwd", new object[] {
                        user});
            LIST = ((string)(results[1]));
            return ((HEADER)(results[0]));
        }
        
        /// <remarks/>
        public void IDM_SUNAC_392_validatePwdAsync(user user) {
            this.IDM_SUNAC_392_validatePwdAsync(user, null);
        }
        
        /// <remarks/>
        public void IDM_SUNAC_392_validatePwdAsync(user user, object userState) {
            if ((this.IDM_SUNAC_392_validatePwdOperationCompleted == null)) {
                this.IDM_SUNAC_392_validatePwdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDM_SUNAC_392_validatePwdOperationCompleted);
            }
            this.InvokeAsync("IDM_SUNAC_392_validatePwd", new object[] {
                        user}, this.IDM_SUNAC_392_validatePwdOperationCompleted, userState);
        }
        
        private void OnIDM_SUNAC_392_validatePwdOperationCompleted(object arg) {
            if ((this.IDM_SUNAC_392_validatePwdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDM_SUNAC_392_validatePwdCompleted(this, new IDM_SUNAC_392_validatePwdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ekingwin.com/esb/header/v1")]
    [System.Xml.Serialization.XmlRootAttribute("commonHeader", Namespace="http://www.ekingwin.com/esb/header/v1", IsNullable=false)]
    public partial class Header : System.Web.Services.Protocols.SoapHeader {
        
        private string bIZTRANSACTIONIDField;
        
        private string cOUNTField;
        
        private string cONSUMERField;
        
        private System.DateTime sRVLEVELField;
        
        private string aCCOUNTField;
        
        private string pASSWORDField;
        
        /// <remarks/>
        public string BIZTRANSACTIONID {
            get {
                return this.bIZTRANSACTIONIDField;
            }
            set {
                this.bIZTRANSACTIONIDField = value;
            }
        }
        
        /// <remarks/>
        public string COUNT {
            get {
                return this.cOUNTField;
            }
            set {
                this.cOUNTField = value;
            }
        }
        
        /// <remarks/>
        public string CONSUMER {
            get {
                return this.cONSUMERField;
            }
            set {
                this.cONSUMERField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SRVLEVEL {
            get {
                return this.sRVLEVELField;
            }
            set {
                this.sRVLEVELField = value;
            }
        }
        
        /// <remarks/>
        public string ACCOUNT {
            get {
                return this.aCCOUNTField;
            }
            set {
                this.aCCOUNTField = value;
            }
        }
        
        /// <remarks/>
        public string PASSWORD {
            get {
                return this.pASSWORDField;
            }
            set {
                this.pASSWORDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ekingwin.com/esb/IDM_SUNAC_392_validatePwd")]
    public partial class HEADER {
        
        private string bIZTRANSACTIONIDField;
        
        private string rESULTField;
        
        private string eRRORCODEField;
        
        private string eRRORINFOField;
        
        private string cOMMENTSField;
        
        private string sUCCESSCOUNTField;
        
        /// <remarks/>
        public string BIZTRANSACTIONID {
            get {
                return this.bIZTRANSACTIONIDField;
            }
            set {
                this.bIZTRANSACTIONIDField = value;
            }
        }
        
        /// <remarks/>
        public string RESULT {
            get {
                return this.rESULTField;
            }
            set {
                this.rESULTField = value;
            }
        }
        
        /// <remarks/>
        public string ERRORCODE {
            get {
                return this.eRRORCODEField;
            }
            set {
                this.eRRORCODEField = value;
            }
        }
        
        /// <remarks/>
        public string ERRORINFO {
            get {
                return this.eRRORINFOField;
            }
            set {
                this.eRRORINFOField = value;
            }
        }
        
        /// <remarks/>
        public string COMMENTS {
            get {
                return this.cOMMENTSField;
            }
            set {
                this.cOMMENTSField = value;
            }
        }
        
        /// <remarks/>
        public string SUCCESSCOUNT {
            get {
                return this.sUCCESSCOUNTField;
            }
            set {
                this.sUCCESSCOUNTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ekingwin.com/esb/IDM_SUNAC_392_validatePwd")]
    public partial class user {
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void IDM_SUNAC_392_validatePwdCompletedEventHandler(object sender, IDM_SUNAC_392_validatePwdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDM_SUNAC_392_validatePwdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDM_SUNAC_392_validatePwdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HEADER Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HEADER)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string LIST {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591