//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunacCADApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sappoqas.sunac.com.cn:50100/XISOAPAdapter/MessageServlet?senderParty=&send" +
            "erService=BC_MDM&receiverParty=&receiverService=&interface=SI_MD_COMMON_OUT&inte" +
            "rfaceNamespace=urn%3ASunac%3Acom%3Amdm%3Aproject")]
        public string SunacCADApp_cn_com_sunac_sappoqas_SI_MD_COMMON_OUTService {
            get {
                return ((string)(this["SunacCADApp_cn_com_sunac_sappoqas_SI_MD_COMMON_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.2.219:8001/WP_SUNAC/APP_CAD_SERVICES/Proxy_Services/TA_BPM/CAD_SUN" +
            "AC_564_WriteSAPXmlToBPM_PS")]
        public string SunacCADApp_WeService_BPM_WriteSAP_CAD_SUNAC_564_WriteSAPXmlToBPM_ptt_bindingQSService {
            get {
                return ((string)(this["SunacCADApp_WeService_BPM_WriteSAP_CAD_SUNAC_564_WriteSAPXmlToBPM_ptt_bindingQSSe" +
                    "rvice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.2.219:8001/WP_SUNAC/APP_CAD_SERVICES/Proxy_Services/TA_BPM/CAD_SUN" +
            "AC_565_UpdateAndApproveFlow_PS")]
        public string SunacCADApp_WebService_UpdataAndApproveFlow_CAD_SUNAC_565_UpdateAndApproveFlow_ptt_bindingQSService {
            get {
                return ((string)(this["SunacCADApp_WebService_UpdataAndApproveFlow_CAD_SUNAC_565_UpdateAndApproveFlow_pt" +
                    "t_bindingQSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.2.219:8001/WP_SUNAC/APP_PUBLIC_SERVICES/Proxy_Services/TA_IDM/PUBL" +
            "IC_SUNAC_300_queryIdmUserData_PS")]
        public string SunacCADApp_WebService_Idm_User_PUBLIC_SUNAC_300_queryIdmUserData_ptt_bindingQSService {
            get {
                return ((string)(this["SunacCADApp_WebService_Idm_User_PUBLIC_SUNAC_300_queryIdmUserData_ptt_bindingQSSe" +
                    "rvice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.2.219:8001/WP_SUNAC/APP_PUBLIC_SERVICES/Proxy_Services/TA_IDM/PUBL" +
            "IC_SUNAC_301_queryIdmOrgData_PS")]
        public string SunacCADApp_WebService_IDM_Public_PUBLIC_SUNAC_301_queryIdmOrgData_ptt_bindingQSService {
            get {
                return ((string)(this["SunacCADApp_WebService_IDM_Public_PUBLIC_SUNAC_301_queryIdmOrgData_ptt_bindingQSS" +
                    "ervice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.2.219:8001/WP_SUNAC/APP_IDM_SERVICES/Proxy_Services/TA_EOP/IDM_SUN" +
            "AC_392_validatePwd_PS")]
        public string SunacCADApp_WebService932_IDM_SUNAC_392_validatePwd_ptt_bindingQSService {
            get {
                return ((string)(this["SunacCADApp_WebService932_IDM_SUNAC_392_validatePwd_ptt_bindingQSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.2.219:8001/WP_SUNAC/APP_CAD_SERVICES/Proxy_Services/TA_BPM/CAD_SUN" +
            "AC_566_DoInvalid_PS")]
        public string SunacCADApp_WebServiceSunacBPM_DoInvalid_CAD_SUNAC_566_DoInvalid_ptt_bindingQSService {
            get {
                return ((string)(this["SunacCADApp_WebServiceSunacBPM_DoInvalid_CAD_SUNAC_566_DoInvalid_ptt_bindingQSSer" +
                    "vice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.2.219:8001/WP_SUNAC/APP_CAD_SERVICES/Proxy_Services/TA_BPM/CAD_SUN" +
            "AC_567_GetFlowState_PS")]
        public string SunacCADApp_WebService_GetFlowState_CAD_SUNAC_567_GetFlowState_ptt_bindingQSService {
            get {
                return ((string)(this["SunacCADApp_WebService_GetFlowState_CAD_SUNAC_567_GetFlowState_ptt_bindingQSServi" +
                    "ce"]));
            }
        }
    }
}
