//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace SunacCADApp.Test.WebBPMService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BMPServiceSoap", Namespace="http://tempuri.org/")]
    public partial class BMPService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuditOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReworkOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveCloseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BMPService() {
            this.Url = global::SunacCADApp.Test.Properties.Settings.Default.SunacCADApp_Test_WebBPMService_BMPService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateResultCompletedEventHandler CreateResultCompleted;
        
        /// <remarks/>
        public event AuditCompletedEventHandler AuditCompleted;
        
        /// <remarks/>
        public event ReworkCompletedEventHandler ReworkCompleted;
        
        /// <remarks/>
        public event ApproveCloseCompletedEventHandler ApproveCloseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("E_RESPONSE")]
        public Rsp_Result CreateResult(Bpm_Req_CreateResult I_REQUEST) {
            object[] results = this.Invoke("CreateResult", new object[] {
                        I_REQUEST});
            return ((Rsp_Result)(results[0]));
        }
        
        /// <remarks/>
        public void CreateResultAsync(Bpm_Req_CreateResult I_REQUEST) {
            this.CreateResultAsync(I_REQUEST, null);
        }
        
        /// <remarks/>
        public void CreateResultAsync(Bpm_Req_CreateResult I_REQUEST, object userState) {
            if ((this.CreateResultOperationCompleted == null)) {
                this.CreateResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateResultOperationCompleted);
            }
            this.InvokeAsync("CreateResult", new object[] {
                        I_REQUEST}, this.CreateResultOperationCompleted, userState);
        }
        
        private void OnCreateResultOperationCompleted(object arg) {
            if ((this.CreateResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateResultCompleted(this, new CreateResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Audit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("E_RESPONSE")]
        public Bpm_Rsp_Result Audit(Bpm_Req_Audit I_REQUEST) {
            object[] results = this.Invoke("Audit", new object[] {
                        I_REQUEST});
            return ((Bpm_Rsp_Result)(results[0]));
        }
        
        /// <remarks/>
        public void AuditAsync(Bpm_Req_Audit I_REQUEST) {
            this.AuditAsync(I_REQUEST, null);
        }
        
        /// <remarks/>
        public void AuditAsync(Bpm_Req_Audit I_REQUEST, object userState) {
            if ((this.AuditOperationCompleted == null)) {
                this.AuditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuditOperationCompleted);
            }
            this.InvokeAsync("Audit", new object[] {
                        I_REQUEST}, this.AuditOperationCompleted, userState);
        }
        
        private void OnAuditOperationCompleted(object arg) {
            if ((this.AuditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuditCompleted(this, new AuditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Rework", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("E_RESPONSE")]
        public Bpm_Rsp_Result Rework(Bpm_Req_Rework I_REQUEST) {
            object[] results = this.Invoke("Rework", new object[] {
                        I_REQUEST});
            return ((Bpm_Rsp_Result)(results[0]));
        }
        
        /// <remarks/>
        public void ReworkAsync(Bpm_Req_Rework I_REQUEST) {
            this.ReworkAsync(I_REQUEST, null);
        }
        
        /// <remarks/>
        public void ReworkAsync(Bpm_Req_Rework I_REQUEST, object userState) {
            if ((this.ReworkOperationCompleted == null)) {
                this.ReworkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReworkOperationCompleted);
            }
            this.InvokeAsync("Rework", new object[] {
                        I_REQUEST}, this.ReworkOperationCompleted, userState);
        }
        
        private void OnReworkOperationCompleted(object arg) {
            if ((this.ReworkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReworkCompleted(this, new ReworkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ApproveClose", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("E_RESPONSE")]
        public Bpm_Rsp_Result ApproveClose(Bpm_Req_ApproveClose I_REQUEST) {
            object[] results = this.Invoke("ApproveClose", new object[] {
                        I_REQUEST});
            return ((Bpm_Rsp_Result)(results[0]));
        }
        
        /// <remarks/>
        public void ApproveCloseAsync(Bpm_Req_ApproveClose I_REQUEST) {
            this.ApproveCloseAsync(I_REQUEST, null);
        }
        
        /// <remarks/>
        public void ApproveCloseAsync(Bpm_Req_ApproveClose I_REQUEST, object userState) {
            if ((this.ApproveCloseOperationCompleted == null)) {
                this.ApproveCloseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveCloseOperationCompleted);
            }
            this.InvokeAsync("ApproveClose", new object[] {
                        I_REQUEST}, this.ApproveCloseOperationCompleted, userState);
        }
        
        private void OnApproveCloseOperationCompleted(object arg) {
            if ((this.ApproveCloseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveCloseCompleted(this, new ApproveCloseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bpm_Req_CreateResult {
        
        private Bpm_Req_BaseInfo rEQ_BASEINFOField;
        
        private Bpm_Req_CreateResult_Message mESSAGEField;
        
        /// <remarks/>
        public Bpm_Req_BaseInfo REQ_BASEINFO {
            get {
                return this.rEQ_BASEINFOField;
            }
            set {
                this.rEQ_BASEINFOField = value;
            }
        }
        
        /// <remarks/>
        public Bpm_Req_CreateResult_Message MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bpm_Req_BaseInfo {
        
        private string rEQ_TRACE_IDField;
        
        private string rEQ_SEND_TIMEField;
        
        private string rEQ_SRC_SYSField;
        
        private string rEQ_TAR_SYSField;
        
        private string rEQ_SERVER_NAMEField;
        
        private int rEQ_SYN_FLAGField;
        
        private string rEQ_BSN_IDField;
        
        private int rEQ_RETRY_TIMESField;
        
        private int rEQ_REPEAT_FLAGField;
        
        private int rEQ_REPEAT_CYCLEField;
        
        private string bIZTRANSACTIONIDField;
        
        private int cOUNTField;
        
        /// <remarks/>
        public string REQ_TRACE_ID {
            get {
                return this.rEQ_TRACE_IDField;
            }
            set {
                this.rEQ_TRACE_IDField = value;
            }
        }
        
        /// <remarks/>
        public string REQ_SEND_TIME {
            get {
                return this.rEQ_SEND_TIMEField;
            }
            set {
                this.rEQ_SEND_TIMEField = value;
            }
        }
        
        /// <remarks/>
        public string REQ_SRC_SYS {
            get {
                return this.rEQ_SRC_SYSField;
            }
            set {
                this.rEQ_SRC_SYSField = value;
            }
        }
        
        /// <remarks/>
        public string REQ_TAR_SYS {
            get {
                return this.rEQ_TAR_SYSField;
            }
            set {
                this.rEQ_TAR_SYSField = value;
            }
        }
        
        /// <remarks/>
        public string REQ_SERVER_NAME {
            get {
                return this.rEQ_SERVER_NAMEField;
            }
            set {
                this.rEQ_SERVER_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public int REQ_SYN_FLAG {
            get {
                return this.rEQ_SYN_FLAGField;
            }
            set {
                this.rEQ_SYN_FLAGField = value;
            }
        }
        
        /// <remarks/>
        public string REQ_BSN_ID {
            get {
                return this.rEQ_BSN_IDField;
            }
            set {
                this.rEQ_BSN_IDField = value;
            }
        }
        
        /// <remarks/>
        public int REQ_RETRY_TIMES {
            get {
                return this.rEQ_RETRY_TIMESField;
            }
            set {
                this.rEQ_RETRY_TIMESField = value;
            }
        }
        
        /// <remarks/>
        public int REQ_REPEAT_FLAG {
            get {
                return this.rEQ_REPEAT_FLAGField;
            }
            set {
                this.rEQ_REPEAT_FLAGField = value;
            }
        }
        
        /// <remarks/>
        public int REQ_REPEAT_CYCLE {
            get {
                return this.rEQ_REPEAT_CYCLEField;
            }
            set {
                this.rEQ_REPEAT_CYCLEField = value;
            }
        }
        
        /// <remarks/>
        public string BIZTRANSACTIONID {
            get {
                return this.bIZTRANSACTIONIDField;
            }
            set {
                this.bIZTRANSACTIONIDField = value;
            }
        }
        
        /// <remarks/>
        public int COUNT {
            get {
                return this.cOUNTField;
            }
            set {
                this.cOUNTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bpm_Req_ApproveClose_Param {
        
        private string strBTIDField;
        
        private string strBOIDField;
        
        private string iProcInstIDField;
        
        private string eProcessInstanceResultField;
        
        private string strCommentField;
        
        private string dtTimeField;
        
        /// <remarks/>
        public string strBTID {
            get {
                return this.strBTIDField;
            }
            set {
                this.strBTIDField = value;
            }
        }
        
        /// <remarks/>
        public string strBOID {
            get {
                return this.strBOIDField;
            }
            set {
                this.strBOIDField = value;
            }
        }
        
        /// <remarks/>
        public string iProcInstID {
            get {
                return this.iProcInstIDField;
            }
            set {
                this.iProcInstIDField = value;
            }
        }
        
        /// <remarks/>
        public string eProcessInstanceResult {
            get {
                return this.eProcessInstanceResultField;
            }
            set {
                this.eProcessInstanceResultField = value;
            }
        }
        
        /// <remarks/>
        public string strComment {
            get {
                return this.strCommentField;
            }
            set {
                this.strCommentField = value;
            }
        }
        
        /// <remarks/>
        public string dtTime {
            get {
                return this.dtTimeField;
            }
            set {
                this.dtTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bpm_Req_ApproveClose_Message {
        
        private Bpm_Req_ApproveClose_Param rEQ_ITEMField;
        
        /// <remarks/>
        public Bpm_Req_ApproveClose_Param REQ_ITEM {
            get {
                return this.rEQ_ITEMField;
            }
            set {
                this.rEQ_ITEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bpm_Req_ApproveClose {
        
        private Bpm_Req_BaseInfo rEQ_BASEINFOField;
        
        private Bpm_Req_ApproveClose_Message mESSAGEField;
        
        /// <remarks/>
        public Bpm_Req_BaseInfo REQ_BASEINFO {
            get {
                return this.rEQ_BASEINFOField;
            }
            set {
                this.rEQ_BASEINFOField = value;
            }
        }
        
        /// <remarks/>
        public Bpm_Req_ApproveClose_Message MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bpm_Req_Rewok_Param {
        
        private string strBTIDField;
        
        private string strBOIDField;
        
        private string iProcInstIDField;
        
        private string strStepNameField;
        
        private string strApproverIdField;
        
        private string eActionField;
        
        private string strCommentField;
        
        private string dtTimeField;
        
        /// <remarks/>
        public string strBTID {
            get {
                return this.strBTIDField;
            }
            set {
                this.strBTIDField = value;
            }
        }
        
        /// <remarks/>
        public string strBOID {
            get {
                return this.strBOIDField;
            }
            set {
                this.strBOIDField = value;
            }
        }
        
        /// <remarks/>
        public string iProcInstID {
            get {
                return this.iProcInstIDField;
            }
            set {
                this.iProcInstIDField = value;
            }
        }
        
        /// <remarks/>
        public string strStepName {
            get {
                return this.strStepNameField;
            }
            set {
                this.strStepNameField = value;
            }
        }
        
        /// <remarks/>
        public string strApproverId {
            get {
                return this.strApproverIdField;
            }
            set {
                this.strApproverIdField = value;
            }
        }
        
        /// <remarks/>
        public string eAction {
            get {
                return this.eActionField;
            }
            set {
                this.eActionField = value;
            }
        }
        
        /// <remarks/>
        public string strComment {
            get {
                return this.strCommentField;
            }
            set {
                this.strCommentField = value;
            }
        }
        
        /// <remarks/>
        public string dtTime {
            get {
                return this.dtTimeField;
            }
            set {
                this.dtTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bpm_Req_Rework_Message {
        
        private Bpm_Req_Rewok_Param rEQ_ITEMField;
        
        /// <remarks/>
        public Bpm_Req_Rewok_Param REQ_ITEM {
            get {
                return this.rEQ_ITEMField;
            }
            set {
                this.rEQ_ITEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bpm_Req_Rework {
        
        private Bpm_Req_BaseInfo rEQ_BASEINFOField;
        
        private Bpm_Req_Rework_Message mESSAGEField;
        
        /// <remarks/>
        public Bpm_Req_BaseInfo REQ_BASEINFO {
            get {
                return this.rEQ_BASEINFOField;
            }
            set {
                this.rEQ_BASEINFOField = value;
            }
        }
        
        /// <remarks/>
        public Bpm_Req_Rework_Message MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bpm_Req_Audit_Param {
        
        private string strBTIDField;
        
        private string strBOIDField;
        
        private string iProcInstIDField;
        
        private string strStepNameField;
        
        private string strApproverIdField;
        
        private string eActionField;
        
        private string strCommentField;
        
        private string dtTimeField;
        
        /// <remarks/>
        public string strBTID {
            get {
                return this.strBTIDField;
            }
            set {
                this.strBTIDField = value;
            }
        }
        
        /// <remarks/>
        public string strBOID {
            get {
                return this.strBOIDField;
            }
            set {
                this.strBOIDField = value;
            }
        }
        
        /// <remarks/>
        public string iProcInstID {
            get {
                return this.iProcInstIDField;
            }
            set {
                this.iProcInstIDField = value;
            }
        }
        
        /// <remarks/>
        public string strStepName {
            get {
                return this.strStepNameField;
            }
            set {
                this.strStepNameField = value;
            }
        }
        
        /// <remarks/>
        public string strApproverId {
            get {
                return this.strApproverIdField;
            }
            set {
                this.strApproverIdField = value;
            }
        }
        
        /// <remarks/>
        public string eAction {
            get {
                return this.eActionField;
            }
            set {
                this.eActionField = value;
            }
        }
        
        /// <remarks/>
        public string strComment {
            get {
                return this.strCommentField;
            }
            set {
                this.strCommentField = value;
            }
        }
        
        /// <remarks/>
        public string dtTime {
            get {
                return this.dtTimeField;
            }
            set {
                this.dtTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bpm_Req_Audit_Message {
        
        private Bpm_Req_Audit_Param rEQ_ITEMField;
        
        /// <remarks/>
        public Bpm_Req_Audit_Param REQ_ITEM {
            get {
                return this.rEQ_ITEMField;
            }
            set {
                this.rEQ_ITEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bpm_Req_Audit {
        
        private Bpm_Req_BaseInfo rEQ_BASEINFOField;
        
        private Bpm_Req_Audit_Message mESSAGEField;
        
        /// <remarks/>
        public Bpm_Req_BaseInfo REQ_BASEINFO {
            get {
                return this.rEQ_BASEINFOField;
            }
            set {
                this.rEQ_BASEINFOField = value;
            }
        }
        
        /// <remarks/>
        public Bpm_Req_Audit_Message MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bpm_Rsp_Param {
        
        private int codeField;
        
        private int successField;
        
        private int errorField;
        
        private int eProcessInstanceResultField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public int Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public int Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public int EProcessInstanceResult {
            get {
                return this.eProcessInstanceResultField;
            }
            set {
                this.eProcessInstanceResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bpm_Rsp_Message {
        
        private Bpm_Rsp_Param rSP_ITEMField;
        
        /// <remarks/>
        public Bpm_Rsp_Param RSP_ITEM {
            get {
                return this.rSP_ITEMField;
            }
            set {
                this.rSP_ITEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bpm_Rsp_BaseInfo {
        
        private string rSP_TRACE_IDField;
        
        private string rSP_REQ_TRACEIDField;
        
        private string rSP_SEND_TIMEField;
        
        private string rSP_SRC_SYSField;
        
        private string rSP_TAR_SYSField;
        
        private string rSP_SERVER_NAMEField;
        
        private string rSP_BSN_IDField;
        
        private int rSP_RETRY_TIMESField;
        
        private int rSP_STATUS_CODEField;
        
        private string rSP_STATUS_MSGField;
        
        private string bIZTRANSACTIONIDField;
        
        private int rESULTField;
        
        /// <remarks/>
        public string RSP_TRACE_ID {
            get {
                return this.rSP_TRACE_IDField;
            }
            set {
                this.rSP_TRACE_IDField = value;
            }
        }
        
        /// <remarks/>
        public string RSP_REQ_TRACEID {
            get {
                return this.rSP_REQ_TRACEIDField;
            }
            set {
                this.rSP_REQ_TRACEIDField = value;
            }
        }
        
        /// <remarks/>
        public string RSP_SEND_TIME {
            get {
                return this.rSP_SEND_TIMEField;
            }
            set {
                this.rSP_SEND_TIMEField = value;
            }
        }
        
        /// <remarks/>
        public string RSP_SRC_SYS {
            get {
                return this.rSP_SRC_SYSField;
            }
            set {
                this.rSP_SRC_SYSField = value;
            }
        }
        
        /// <remarks/>
        public string RSP_TAR_SYS {
            get {
                return this.rSP_TAR_SYSField;
            }
            set {
                this.rSP_TAR_SYSField = value;
            }
        }
        
        /// <remarks/>
        public string RSP_SERVER_NAME {
            get {
                return this.rSP_SERVER_NAMEField;
            }
            set {
                this.rSP_SERVER_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string RSP_BSN_ID {
            get {
                return this.rSP_BSN_IDField;
            }
            set {
                this.rSP_BSN_IDField = value;
            }
        }
        
        /// <remarks/>
        public int RSP_RETRY_TIMES {
            get {
                return this.rSP_RETRY_TIMESField;
            }
            set {
                this.rSP_RETRY_TIMESField = value;
            }
        }
        
        /// <remarks/>
        public int RSP_STATUS_CODE {
            get {
                return this.rSP_STATUS_CODEField;
            }
            set {
                this.rSP_STATUS_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string RSP_STATUS_MSG {
            get {
                return this.rSP_STATUS_MSGField;
            }
            set {
                this.rSP_STATUS_MSGField = value;
            }
        }
        
        /// <remarks/>
        public string BIZTRANSACTIONID {
            get {
                return this.bIZTRANSACTIONIDField;
            }
            set {
                this.bIZTRANSACTIONIDField = value;
            }
        }
        
        /// <remarks/>
        public int RESULT {
            get {
                return this.rESULTField;
            }
            set {
                this.rESULTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bpm_Rsp_Result {
        
        private Bpm_Rsp_BaseInfo rSP_BASEINFOField;
        
        private Bpm_Rsp_Message mESSAGEField;
        
        /// <remarks/>
        public Bpm_Rsp_BaseInfo RSP_BASEINFO {
            get {
                return this.rSP_BASEINFOField;
            }
            set {
                this.rSP_BASEINFOField = value;
            }
        }
        
        /// <remarks/>
        public Bpm_Rsp_Message MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Rsp_Result {
        
        private Bpm_Rsp_Result e_RESPONSEField;
        
        /// <remarks/>
        public Bpm_Rsp_Result E_RESPONSE {
            get {
                return this.e_RESPONSEField;
            }
            set {
                this.e_RESPONSEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bpm_Req_CreateResult_Param {
        
        private string strBTIDField;
        
        private string strBOIDField;
        
        private string bSuccessField;
        
        private string iProcInstIDField;
        
        private string procURLField;
        
        private string strMessageField;
        
        /// <remarks/>
        public string strBTID {
            get {
                return this.strBTIDField;
            }
            set {
                this.strBTIDField = value;
            }
        }
        
        /// <remarks/>
        public string strBOID {
            get {
                return this.strBOIDField;
            }
            set {
                this.strBOIDField = value;
            }
        }
        
        /// <remarks/>
        public string bSuccess {
            get {
                return this.bSuccessField;
            }
            set {
                this.bSuccessField = value;
            }
        }
        
        /// <remarks/>
        public string iProcInstID {
            get {
                return this.iProcInstIDField;
            }
            set {
                this.iProcInstIDField = value;
            }
        }
        
        /// <remarks/>
        public string procURL {
            get {
                return this.procURLField;
            }
            set {
                this.procURLField = value;
            }
        }
        
        /// <remarks/>
        public string strMessage {
            get {
                return this.strMessageField;
            }
            set {
                this.strMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bpm_Req_CreateResult_Message {
        
        private Bpm_Req_CreateResult_Param rEQ_ITEMField;
        
        /// <remarks/>
        public Bpm_Req_CreateResult_Param REQ_ITEM {
            get {
                return this.rEQ_ITEMField;
            }
            set {
                this.rEQ_ITEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void CreateResultCompletedEventHandler(object sender, CreateResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Rsp_Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Rsp_Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void AuditCompletedEventHandler(object sender, AuditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Bpm_Rsp_Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Bpm_Rsp_Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ReworkCompletedEventHandler(object sender, ReworkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReworkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReworkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Bpm_Rsp_Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Bpm_Rsp_Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ApproveCloseCompletedEventHandler(object sender, ApproveCloseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApproveCloseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApproveCloseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Bpm_Rsp_Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Bpm_Rsp_Result)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591